CREATE TABLE IF NOT EXISTS usuario(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	LOGIN VARCHAR(20),
	SENHA VARCHAR(20)
);


INSERT INTO usuario (NOME, LOGIN, SENHA) VALUES('jean', 'jeanfbs','123');

INSERT INTO usuario (NOME, LOGIN, SENHA) VALUES('Jean fabricio2', 'jeanfbs2','222');